name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main  # or specify the branch you want to track

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Use the stable version of Flutter

      # Verify Flutter installation
      - name: Verify Flutter installation
        run: |
          flutter --version  # This checks if flutter is installed correctly
          which flutter      # This confirms the location of the flutter command

      # Install dependencies (if needed)
      - name: Install dependencies
        run: |
          flutter pub get   # This installs the necessary dependencies

      # Build the web app using Flutter
      - name: Build web app
        run: flutter build web

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BETTER_PLACEMAKING }}
          projectId: better-placemaking
