name: Flutter Web Build and Deploy to Firebase

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: Pipeline-To-Better-Placemaking/actions/checkout@v2 # Forked version of actions/checkout

      - name: Set up Flutter
        uses: Pipeline-To-Better-Placemaking/flutter-action@v2 # Forked version of subosito/flutter-action

      - name: Deploy to Firebase Hosting
        uses: Pipeline-To-Better-Placemaking/firebase-hosting-action@v0.2.0 # Forked version of wzieba/firebase-hosting-action


      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0' # Specify the Flutter version you want to use

      # Install dependencies
      - name: Install dependencies
        run: |
          flutter pub get

      # Run the Flutter build for web with Firebase API keys as environment variables
      - name: Build Flutter web
        run: |
          flutter build web \
            --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
            --dart-define=FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} \
            --dart-define=FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} \
            --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
            --dart-define=FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
            --dart-define=FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
            --dart-define=FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} \
            --dart-define=FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: wzieba/Firebase-Hosting-Action@v0.2.0
        with:
          firebase_token: ${{ secrets.FIREBASE_AUTH_TOKEN }} # Firebase Auth Token
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}  # Firebase project ID
